import { describe, expect, it } from "vitest";

import * as published from "#authoring/index.ts";

const SURFACE = [
  "absoluteCenter",
  "alphaScale",
  "BACKGROUNDS",
  "backgrounds",
  "bento",
  "bentoCell",
  "BORDERS",
  "borders",
  "center",
  "cluster",
  "colorScale",
  "compoundClassName",
  "contract",
  "contrast",
  "controls",
  "controlSizes",
  "cover",
  "deepMerge",
  "definePreset",
  "defineRecipe",
  "defineSlotRecipe",
  "defineStyles",
  "defineTheme",
  "dense",
  "divider",
  "families",
  "field",
  "flex",
  "floating",
  "fontSizes",
  "FOREGROUNDS",
  "foregrounds",
  "frame",
  "gaps",
  "grid",
  "hstack",
  "HUES",
  "iconOnly",
  "icons",
  "iconSizes",
  "insets",
  "interactive",
  "link",
  "LOOKS",
  "lookVariants",
  "luminance",
  "MODES",
  "motion",
  "neutralFills",
  "oklch",
  "overlay",
  "paletteAlias",
  "paletteRoles",
  "palettes",
  "PALETTES",
  "radii",
  "readable",
  "reel",
  "responsive",
  "ROLES",
  "scrollable",
  "shadows",
  "sidebar",
  "simpleGrid",
  "slides",
  "slotsOf",
  "stack",
  "sticky",
  "STATUSES",
  "statusVariants",
  "surface",
  "switcher",
  "touchTarget",
  "typography",
  "visuallyHidden",
  "vstack",
];

describe("authoring", () => {
  it("publishes the vocabulary a recipe and a theme are written in", () => {
    expect(Object.keys(published).toSorted()).toStrictEqual(SURFACE.toSorted());
  });

  it("publishes nothing from the generated runtime", () => {
    expect(Object.keys(published)).not.toContain("css");
    expect(Object.keys(published)).not.toContain("styled");
  });
});
