/**
 * Generates the declaration file that types every namespace's keys.
 *
 * @remarks
 *   Each string becomes a string literal type, so an unknown key and a dropped placeholder are both
 *   editor errors.
 */

import { type CatalogueIndex, mergedWords, ofLanguage, type Words } from "#emit.ts";

/**
 * The package whose `Resources` interface the types are added to.
 */
export const FOUNDATION = "@stealthscale/provider-i18n";

/**
 * The header the generated file opens with, telling a reader not to edit it.
 */
const HEADER = [
  "// Generated by @stealthscale/vite-plugin-i18n from the catalogues found. Do not edit: change",
  "// the words in locales/<language>/<namespace>.json and this file follows.",
  "",
  "export {};",
  "",
].join("\n");

/**
 * Renders one namespace's contents as an object type, nested as the contents are.
 *
 * @param words - The contents, nested as the catalogue stores them.
 * @param depth - The current nesting level, which sets the indentation.
 * @returns The object type as TypeScript source.
 */
function typed(words: Words, depth: number): string {
  const pad = "  ".repeat(depth);
  const members = Object.entries(words)
    .toSorted(([one], [other]) => one.localeCompare(other))
    .map(
      ([key, value]) =>
        `${pad}  ${JSON.stringify(key)}: ${typeof value === "string" ? JSON.stringify(value) : typed(value, depth + 1)};`,
    );

  return `{\n${members.join("\n")}\n${pad}}`;
}

/**
 * Renders the augmentation that adds every namespace to the foundation's `Resources`.
 *
 * @param index - The indexed catalogues.
 * @param fallback - The language whose strings type the keys.
 * @returns The declaration file as TypeScript source.
 */
export function declared(index: CatalogueIndex, fallback: string): string {
  const namespaces = [...ofLanguage(index, fallback).entries()].toSorted(([one], [other]) =>
    one.localeCompare(other),
  );
  const members = namespaces.map(
    ([namespace, files]) => `    ${JSON.stringify(namespace)}: ${typed(mergedWords(files), 2)};`,
  );

  return `${HEADER}declare module ${JSON.stringify(FOUNDATION)} {\n  interface Resources {\n${members.join("\n")}\n  }\n}\n`;
}
