import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { withScratchWorkspace } from "@stealthscale/testing";

import { indexed } from "#emit.ts";
import { APP, WORKSPACE } from "#find.fixtures.ts";
import { found } from "#find.ts";
import { declared, FOUNDATION } from "#typegen.ts";

/**
 * Writes the types for the fixture workspace.
 *
 * @returns The declaration file's source.
 */
function typed(): string {
  return withScratchWorkspace(WORKSPACE, (scratch) =>
    declared(indexed(found(join(scratch.root, APP))), "en"),
  );
}

describe("declared", () => {
  it("declares the module the foundation publishes Resources from", () => {
    const source = typed();

    expect(source).toContain(`declare module "${FOUNDATION}"`);
    expect(source).toContain("interface Resources {");
  });

  it("types a word as its string literal", () => {
    expect(typed()).toMatch(
      /"controls": \{\n\s+"pages_one": "\{\{count\}\} page";\n\s+"pages_other": "\{\{count\}\} pages";\n\s+\};/u,
    );
  });

  it("nests the type as the catalogue nests the words", () => {
    expect(typed()).toMatch(
      /"overlays": \{\n\s+"commands": "Actions";\n\s+"menu": "Menu";\n\s+"nested": \{\n\s+"close": "Close \{\{what\}\}";\n\s+\};\n\s+\};/u,
    );
  });

  it("adds every namespace found", () => {
    expect(typed()).toContain('"site": {');
  });

  it("opens with a do-not-edit header", () => {
    expect(typed().startsWith("// Generated by @stealthscale/vite-plugin-i18n")).toBe(true);
  });

  it("exports an empty object so the file is a module", () => {
    expect(typed()).toContain("export {};");
  });

  it("declares an empty interface when no catalogue was found", () => {
    expect(declared(new Map(), "en")).toContain("interface Resources {\n\n  }");
  });
});
